Arquivo de relatório de análise léxica
Equipe E02 - Magenta
Integrantes:

->Alfonso Carlos Paes Martinez Junior	 TEL: (71) 9 8180-0054	 EMAIL: engmartinez00@gmail.com
->Lis da Silva Azevedo			 TEL: (71) 9 9214-2580	 EMAIL: lisazevedo3@gmail.com
->Leonardo de Andrade Santana		 TEL: (71) 9 9407-5108	 EMAIL: devleonardoandrade@gmail.com
->Daniel Campos Tavares Gomes		 TEL: (71) 9 9730-7988	 EMAIL: daniel.tavares.3096@gmail.com

Lexeme	| Id	| IndiceTabelaSimbolos
__________________________________________
TEST 	| 0 	| 555
TEST2 	| 1 	| 2
